defaults:
  - _self_
  - model: pyloric

id: "p31_2"
seed_train: 0
seed_simulator: null
seed_evaluate: 0
num_predictives: 100
cores: 1
num_samples_to_estimate_support: 100000
allowed_false_negatives: 0.0001
use_constrained_prior: False
constrained_prior_quanitle: 0.0
sims_per_round: 10000
num_rounds: 1
max_num_epochs: 10000
training_batch_size: 500
stop_after_epochs: 20
num_initial: 100000
density_estimator: "nsf"
ensemble_size: 1
replace_nan_values: False

hydra:
  run:
    dir: ../results/${id}/multiround/${now:%Y_%m_%d}__${now:%H_%M_%S}
  sweep:
    dir: ../results/${id}/multiround/${now:%Y_%m_%d}__${now:%H_%M_%S}__multirun
    subdir: ${hydra.job.num}